packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@prisma/engines": true
  core-js: true
  esbuild: true
  prisma: true
  tesseract.js: true

onlyBuiltDependencies:
  - "@prisma/engines"
  - "core-js"
  - "esbuild"
  - "prisma"
  - "tesseract.js"

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
